#!/usr/bin/env python3
# Jotty Autoprogrammer
import sys
from jot import jot_to_py
from itertools import product

def test_program(code, test):
    """Returns True if the given code satisfies the test."""
    p = jot_to_py(code)
    return eval(test)

def test_bitstrings(length, test):
    """Tests all bitstrings of a given length to see if any of them, when
    interpreted as jot code, satisfy the test.

    Prints out the code if it finds it."""
    for program in product([0, 1], repeat=length):
        try:
            if test_program(program, test):
                return program
        except (KeyboardInterrupt, SystemExit):
            raise
        except:
            pass
    return None

def parse_args():
    import argparse

    parser = argparse.ArgumentParser(prog='jotty',
        epilog='see github for detailed docs & updates',
        description='an automatic jot programmer')

    parser.add_argument('targetfile', help='file containing tests to run')
    parser.add_argument('-v', '--verbose', help='verbose mode',
                        action='store_true')
    parser.add_argument('-i', '--interactive', help='turn on interactive mode',
                        action='store_true')

    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()

    try:
        with open(args.targetfile) as f:
            exec(f.read())
            if not test:
                print('No variable test found in', targetfile, file=sys.stderr)
                sys.exit(2)
    except FileNotFoundError:
        print('File', args.targetfile, 'not found', file=sys.stderr)
        sys.exit(3)
    except:
        print('Error while executing', args.targetfile, file=sys.stderr)
        raise

    length = 0
    while True:
        if args.verbose: print('Testing length', length)

        program = test_bitstrings(length, test)

        if program is not None:
            if args.interactive:
                p = jot_to_py(program)

            print(program)
            break

        length += 1

    if args.interactive:
        import code
        print()
        code.interact(banner='Use p for the jot program', local=locals())
